micronaut:
  application:
    name: micronautFileUpload

  server:
    max-request-size: 16777216 # 1024 * 1024 * 16 = 16 MB, default is 10 MB
    multipart:
      max-file-size: 16777216 # 1024 * 1024 * 16 = 16 MB, default is 1 MB